### ISSUE TITLE
User auth styling

### ISSUE THREAD

**Issue by etgrieco** [etgrieco/EasyFeeds#6]
* Landing page with dummy graphics (screenshot of app: done at end)
* Search bar with (dummy) logo and login button
* Floating modulo

* Consistent fonts and coloring

**Comment by mikeboan** [comment]
like 80% there. errors could look better (and it'd be cool if they didn't change the form size) and the button should be the same width as the inputs. Tiny details like that are key in looking like a pro-level app.

**Comment by etgrieco** [comment]
Thanks! I'll be refining these things tonight and I should hit my milestone comfortably. Also implemented protected routes for the rest of the app, nesting the interface under /i/ as you suggested.
